# Generated by Django 3.2.12 on 2022-07-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20220701_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('date', models.CharField(max_length=30)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.CharField(editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.CharField(editable=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(editable=False, max_length=200),
        ),
    ]
