# Generated by Django 3.2.12 on 2022-07-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20220701_1059'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo2',
        ),
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
